### ISSUE TITLE
No such file or directory: 'MureCom/Train/bbox.txt'

### ISSUE THREAD

**Issue by dain5832** [bcmi/DreamCom-Image-Composition#2]
I executed test.py and got an error 'No such file or directory: 'MureCom/Train/bbox.txt''.
It seems like the train.py does not require bbox.txt.
Could you tell me how can I solve this issue?

**Comment by dain5832** [comment]
Seems like I was supposed to make own bbox.txt file.
I checked it worked after creating bbox,txt,

**Comment by pokaaa** [comment]
> Seems like I was supposed to make own bbox.txt file. I checked it worked after creating bbox,txt,

The bbox.txt of our dataset has been organized and placed in **Murecom/Train/bg/** directory. The path in test.py has been modified accordingly.
